### ISSUE TITLE
Greeting and starting the reviewing process

### ISSUE THREAD

**Issue by sleepylee** [hoang06kx1/koin-example-android#11]
Hi Hoang,
Good to e-meet you again 👋 and thanks for your effort on this submission. It's Trung again and today, I'd like to conduct the feedbacks to you via Issues ticket regarding your performance here. These feedbacks are being built by also other 2 developers to make the least bias and better overall judgment just for your information 🙏

Keep in mind, this is a bidirectional process, so we'd love to hear back from you as well, so please don't hesitate to raise your question/correction in case we missed anything. 😇 Sometimes things we are doing might be different in our approaches, so what I'll try to do here is likely to point out what are those differences.

The 1st Issue I observed is your gitflow model, it doesn't seem to follow this common practice [here](https://datasift.github.io/gitflow/IntroducingGitFlow.html), what I saw mostly from your PRs (#1  #2 #3 #4 ...) the features were developed and committed directly to `master`, then brought back to `develop` without any intermediate branch per implementation.

**Comment by hoang06kx1** [comment]
Hi Trung,
Nice to see you again. 
Thanks for the precious time you and other teammates spent to do the code review.

Your reviews are comprehensive with linked articles for references as well as explanations. I really appreciate it.

For the 1st issue about the git-flow model, I'm unsure about your conclusion that features are committed directly to the `master` branch. Instead, all features are implemented and committed to the `develop` branch. For any hotfix, I created a new local branch to solve the issue then merge it back to the `develop`. All local branches are deleted immediately after being merged back to `develop`.  So on the remote repo only has 2 branches, I believe too many branches on remote is not good at all.

**Comment by sleepylee** [comment]
Hi @hoang06kx1 , I'm glad that you found the feedback useful 🙏. Regarding the branching model, you're right that **your current approach is from develop -> master**, my bad, maybe because I got used to the merging direction from bitbucket 😢  Anyway, regarding the branching model, to our experience it is not bad at all to have multiple branches on remote, unless you keep it forever (better approach is to use TAG). The intermediate branch can be used to keep your works separated and co-exist with the other team member's work. 

Say I'm developing `login` feature and you're developing `payment` feature, so:
- We'll both branch out from `/develop`
- I'm working on my branch `feature/login` and open the PR when it's finish -> `develop`
- You can work on your branch as `feature/payment` and open the PR when it's finish -> `develop`
- Once merged, the remote branch can be deleted, and if there is any conflict, the later PR will show that up and we can coordinate to resolve the conflict accordingly.

That's the idea 😄
