### ISSUE TITLE
Code format is not being used or strange configured from what developers usually have as default, misc..

### ISSUE THREAD

**Issue by sleepylee** [hoang06kx1/koin-example-android#12]
I noticed from your code style is that:
- Some places method calls are very long, exceeding the normal barrier we usually have in Android Studio.
- Spacing is also incorrect at some places.
- Magic numbers are still appearing in some places (check the MainActivity)

It doesn't mean that you're a bad developer just because of the format we're talking here, just so you know that our approach is a bit different here: we'd prefer well-formatted codes to enhance the readability and the joys of reading for the developers, so it does matter to us.

**Comment by hoang06kx1** [comment]
Thanks for pointing out my weird code format.
I totally agree with you code format is very important for us as developers who have to read not only our code but other code, thousand lines of code every day.
I recognized some problems with my code, quite late after submission. The reason:

- Line break on my Android Studio is set at 150 characters length (I'm using a wide monitor), so the auto-format process keeps it a little bit longer than usual.
- `Some spaces are auto inserted unexpectedly` (weird to me, too). I guess the Unikey on Ubuntu auto insert those mysterious spaces when I was switching typing mode. 
- After all, it's my imprudence not to use a code style checker. Lesson learned here.
